import { defineStore } from 'pinia';

export const useRegionStore = defineStore('region', {
  state: () => ({
    subRegions : {
        31: [
          { gugun_code: 1, name: '가평' },
          { gugun_code: 2, name: '고양' },
          { gugun_code: 3, name: '과천' },
          { gugun_code: 4, name: '광명' },
          { gugun_code: 5, name: '광주' },
          { gugun_code: 6, name: '구리' },
          { gugun_code: 7, name: '군포' },
          { gugun_code: 8, name: '김포' },
          { gugun_code: 9, name: '남양주' },
          { gugun_code: 10, name: '동두천' },
          { gugun_code: 11, name: '부천' },
          { gugun_code: 12, name: '성남' },
          { gugun_code: 13, name: '수원' },
          { gugun_code: 14, name: '시흥' },
          { gugun_code: 15, name: '안산' },
          { gugun_code: 16, name: '안성' },
          { gugun_code: 17, name: '안양' },
          { gugun_code: 18, name: '양주' },
          { gugun_code: 19, name: '양평' },
          { gugun_code: 20, name: '여주' },
          { gugun_code: 21, name: '연천' },
          { gugun_code: 22, name: '오산' },
          { gugun_code: 23, name: '용인' },
          { gugun_code: 24, name: '의왕' },
          { gugun_code: 25, name: '의정부' },
          { gugun_code: 26, name: '이천' },
          { gugun_code: 27, name: '파주' },
          { gugun_code: 28, name: '평택' },
          { gugun_code: 29, name: '포천' },
          { gugun_code: 30, name: '하남' },
          { gugun_code: 31, name: '화성' },
        ],
        32: [
          { gugun_code: 1, name: '강릉' },
          { gugun_code: 2, name: '고성' },
          { gugun_code: 3, name: '동해' },
          { gugun_code: 4, name: '삼척' },
          { gugun_code: 5, name: '속초' },
          { gugun_code: 6, name: '양구' },
          { gugun_code: 7, name: '양양' },
          { gugun_code: 8, name: '영월' },
          { gugun_code: 9, name: '원주' },
          { gugun_code: 10, name: '인제' },
          { gugun_code: 11, name: '정선' },
          { gugun_code: 12, name: '철원' },
          { gugun_code: 13, name: '춘천' },
          { gugun_code: 14, name: '태백' },
          { gugun_code: 15, name: '평창' },
          { gugun_code: 16, name: '홍천' },
          { gugun_code: 17, name: '화천' },
          { gugun_code: 18, name: '횡성' },
        ],
        33: [
          { gugun_code: 1, name: '괴산' },
          { gugun_code: 2, name: '단양' },
          { gugun_code: 3, name: '보은' },
          { gugun_code: 4, name: '영동' },
          { gugun_code: 5, name: '옥천' },
          { gugun_code: 6, name: '음성' },
          { gugun_code: 7, name: '제천' },
          { gugun_code: 8, name: '진천' },
          { gugun_code: 9, name: '청원' },
          { gugun_code: 10, name: '청주' },
          { gugun_code: 11, name: '충주' },
          { gugun_code: 12, name: '증평' },
        ],
        34: [
          { gugun_code: 1, name: '공주' },
          { gugun_code: 2, name: '금산' },
          { gugun_code: 3, name: '논산' },
          { gugun_code: 4, name: '당진' },
          { gugun_code: 5, name: '보령' },
          { gugun_code: 6, name: '부여' },
          { gugun_code: 7, name: '서산' },
          { gugun_code: 8, name: '서천' },
          { gugun_code: 9, name: '아산' },
          { gugun_code: 11, name: '예산' },
          { gugun_code: 12, name: '천안' },
          { gugun_code: 13, name: '청양' },
          { gugun_code: 14, name: '태안' },
          { gugun_code: 15, name: '홍성' },
          { gugun_code: 16, name: '계룡' },
        ],
        35: [
            { gugun_code: 1, name: '경산시' },
            { gugun_code: 2, name: '경주시' },
            { gugun_code: 3, name: '고령군' },
            { gugun_code: 4, name: '구미시' },
            { gugun_code: 6, name: '김천시' },
            { gugun_code: 7, name: '문경시' },
            { gugun_code: 8, name: '봉화군' },
            { gugun_code: 9, name: '상주시' },
            { gugun_code: 10, name: '성주군' },
            { gugun_code: 11, name: '안동시' },
            { gugun_code: 12, name: '영덕군' },
            { gugun_code: 13, name: '영양군' },
            { gugun_code: 14, name: '영주시' },
            { gugun_code: 15, name: '영천시' },
            { gugun_code: 16, name: '예천군' },
            { gugun_code: 17, name: '울릉군' },
            { gugun_code: 18, name: '울진군' },
            { gugun_code: 19, name: '의성군' },
            { gugun_code: 20, name: '청도군' },
            { gugun_code: 21, name: '청송군' },
            { gugun_code: 22, name: '칠곡군' },
            { gugun_code: 23, name: '포항시' }
          ],
          36: [
            { gugun_code: 1, name: '거제시' },
            { gugun_code: 2, name: '거창군' },
            { gugun_code: 3, name: '고성군' },
            { gugun_code: 4, name: '김해시' },
            { gugun_code: 5, name: '남해군' },
            { gugun_code: 6, name: '마산시' },
            { gugun_code: 7, name: '밀양시' },
            { gugun_code: 8, name: '사천시' },
            { gugun_code: 9, name: '산청군' },
            { gugun_code: 10, name: '양산시' },
            { gugun_code: 12, name: '의령군' },
            { gugun_code: 13, name: '진주시' },
            { gugun_code: 14, name: '진해시' },
            { gugun_code: 15, name: '창녕군' },
            { gugun_code: 16, name: '창원시' },
            { gugun_code: 17, name: '통영시' },
            { gugun_code: 18, name: '하동군' },
            { gugun_code: 19, name: '함안군' },
            { gugun_code: 20, name: '함양군' },
            { gugun_code: 21, name: '합천군' }
          ],
          37: [
            { gugun_code: 1, name: '고창군' },
            { gugun_code: 2, name: '군산시' },
            { gugun_code: 3, name: '김제시' },
            { gugun_code: 4, name: '남원시' },
            { gugun_code: 5, name: '무주군' },
            { gugun_code: 6, name: '부안군' },
            { gugun_code: 7, name: '순창군' },
            { gugun_code: 8, name: '완주군' },
            { gugun_code: 9, name: '익산시' },
            { gugun_code: 10, name: '임실군' },
            { gugun_code: 11, name: '장수군' },
            { gugun_code: 12, name: '전주시' },
            { gugun_code: 13, name: '정읍시' },
            { gugun_code: 14, name: '진안군' }
          ],
          38: [
            { gugun_code: 1, name: '강진군' },
            { gugun_code: 2, name: '고흥군' },
            { gugun_code: 3, name: '곡성군' },
            { gugun_code: 4, name: '광양시' },
            { gugun_code: 5, name: '구례군' },
            { gugun_code: 6, name: '나주시' },
            { gugun_code: 7, name: '담양군' },
            { gugun_code: 8, name: '목포시' },
            { gugun_code: 9, name: '무안군' },
            { gugun_code: 10, name: '보성군' },
            { gugun_code: 11, name: '순천시' },
            { gugun_code: 12, name: '신안군' },
            { gugun_code: 13, name: '여수시' },
            { gugun_code: 16, name: '영광군' },
            { gugun_code: 17, name: '영암군' },
            { gugun_code: 18, name: '완도군' },
            { gugun_code: 19, name: '장성군' },
            { gugun_code: 20, name: '장흥군' },
            { gugun_code: 21, name: '진도군' },
            { gugun_code: 22, name: '함평군' },
            { gugun_code: 23, name: '해남군' },
            { gugun_code: 24, name: '화순군' }
          ],
        39: [
          { gugun_code: 1, name: '남제주' },
          { gugun_code: 2, name: '북제주' },
          { gugun_code: 3, name: '서귀포' },
          { gugun_code: 4, name: '제주' },
        ],
      }
  }),
  getters: {
    // 특정 `sido_code`의 subRegions를 가져오는 getter
    getSubRegions: (state) => (sido_code) => state.subRegions[sido_code] || [],
  },
});
